// Este arquivo contém dados para todos os campeões do League of Legends
// Em uma aplicação real, esses dados viriam de uma API

// Função para formatar o ID do campeão para o formato correto do DDragon
const formatChampionId = (id: string) => {
  // Casos especiais para nomes compostos
  const specialCases: Record<string, string> = {
    aurelionsol: "AurelionSol",
    drmundo: "DrMundo",
    jarvaniv: "JarvanIV",
    kogmaw: "KogMaw",
    leesin: "LeeSin",
    masteryi: "MasterYi",
    missfortune: "MissFortune",
    nunu: "Nunu",
    reksai: "RekSai",
    tahmkench: "TahmKench",
    twistedfate: "TwistedFate",
    xinzhao: "XinZhao",
  }

  if (specialCases[id.toLowerCase()]) {
    return specialCases[id.toLowerCase()]
  }

  return id.charAt(0).toUpperCase() + id.slice(1)
}

export const championsData = [
  {
    id: "aatrox",
    name: "Aatrox",
    title: "The Darkin Blade",
    roles: ["Fighter", "Tank"],
    image: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_0.jpg`,
    splash: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_0.jpg`,
    difficulty: 3,
  },
  {
    id: "ahri",
    name: "Ahri",
    title: "The Nine-Tailed Fox",
    roles: ["Mage", "Assassin"],
    image: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg`,
    splash: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg`,
    difficulty: 2,
  },
  {
    id: "akali",
    name: "Akali",
    title: "The Rogue Assassin",
    roles: ["Assassin"],
    image: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg`,
    splash: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg`,
    difficulty: 3,
  },
  {
    id: "akshan",
    name: "Akshan",
    title: "The Rogue Sentinel",
    roles: ["Marksman", "Assassin"],
    image: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akshan_0.jpg`,
    splash: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akshan_0.jpg`,
    difficulty: 2,
  },
  {
    id: "alistar",
    name: "Alistar",
    title: "The Minotaur",
    roles: ["Tank", "Support"],
    image: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Alistar_0.jpg`,
    splash: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Alistar_0.jpg`,
    difficulty: 1,
  },
  {
    id: "amumu",
    name: "Amumu",
    title: "The Sad Mummy",
    roles: ["Tank", "Mage"],
    image: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Amumu_0.jpg`,
    splash: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Amumu_0.jpg`,
    difficulty: 1,
  },
  {
    id: "anivia",
    name: "Anivia",
    title: "The Cryophoenix",
    roles: ["Mage", "Support"],
    image: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Anivia_0.jpg`,
    splash: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Anivia_0.jpg`,
    difficulty: 3,
  },
  {
    id: "annie",
    name: "Annie",
    title: "The Dark Child",
    roles: ["Mage"],
    image: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Annie_0.jpg`,
    splash: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Annie_0.jpg`,
    difficulty: 1,
  },
  {
    id: "aphelios",
    name: "Aphelios",
    title: "The Weapon of the Faithful",
    roles: ["Marksman"],
    image: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aphelios_0.jpg`,
    splash: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aphelios_0.jpg`,
    difficulty: 3,
  },
  {
    id: "ashe",
    name: "Ashe",
    title: "The Frost Archer",
    roles: ["Marksman", "Support"],
    image: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ashe_0.jpg`,
    splash: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ashe_0.jpg`,
    difficulty: 1,
  },
  {
    id: "aurelionsol",
    name: "Aurelion Sol",
    title: "The Star Forger",
    roles: ["Mage"],
    image: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/AurelionSol_0.jpg`,
    splash: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/AurelionSol_0.jpg`,
    difficulty: 3,
  },
  {
    id: "azir",
    name: "Azir",
    title: "The Emperor of the Sands",
    roles: ["Mage", "Marksman"],
    image: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Azir_0.jpg`,
    splash: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Azir_0.jpg`,
    difficulty: 3,
  },
  {
    id: "bard",
    name: "Bard",
    title: "The Wandering Caretaker",
    roles: ["Support", "Mage"],
    image: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Bard_0.jpg`,
    splash: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Bard_0.jpg`,
    difficulty: 3,
  },
  {
    id: "blitzcrank",
    name: "Blitzcrank",
    title: "The Great Steam Golem",
    roles: ["Tank", "Support"],
    image: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Blitzcrank_0.jpg`,
    splash: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Blitzcrank_0.jpg`,
    difficulty: 1,
  },
  {
    id: "brand",
    name: "Brand",
    title: "The Burning Vengeance",
    roles: ["Mage"],
    image: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Brand_0.jpg`,
    splash: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Brand_0.jpg`,
    difficulty: 2,
  },
  {
    id: "braum",
    name: "Braum",
    title: "The Heart of the Freljord",
    roles: ["Support", "Tank"],
    image: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Braum_0.jpg`,
    splash: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Braum_0.jpg`,
    difficulty: 2,
  },
  {
    id: "caitlyn",
    name: "Caitlyn",
    title: "The Sheriff of Piltover",
    roles: ["Marksman"],
    image: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Caitlyn_0.jpg`,
    splash: `https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Caitlyn_0.jpg`,
    difficulty: 1,
  },
  {
    id: "camille",
    name: "Camille",
    title: "The Steel Shadow",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/camille.jpg`,
    splash: `/images/splashes/camille.jpg`,
    difficulty: 3,
  },
  {
    id: "cassiopeia",
    name: "Cassiopeia",
    title: "The Serpent's Embrace",
    roles: ["Mage"],
    image: `/images/champions/cassiopeia.jpg`,
    splash: `/images/splashes/cassiopeia.jpg`,
    difficulty: 3,
  },
  {
    id: "chogath",
    name: "Cho'Gath",
    title: "The Terror of the Void",
    roles: ["Tank", "Mage"],
    image: `/images/champions/chogath.jpg`,
    splash: `/images/splashes/chogath.jpg`,
    difficulty: 1,
  },
  {
    id: "corki",
    name: "Corki",
    title: "The Daring Bombardier",
    roles: ["Marksman"],
    image: `/images/champions/corki.jpg`,
    splash: `/images/splashes/corki.jpg`,
    difficulty: 2,
  },
  {
    id: "darius",
    name: "Darius",
    title: "The Hand of Noxus",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/darius.jpg`,
    splash: `/images/splashes/darius.jpg`,
    difficulty: 2,
  },
  {
    id: "diana",
    name: "Diana",
    title: "Scorn of the Moon",
    roles: ["Fighter", "Mage"],
    image: `/images/champions/diana.jpg`,
    splash: `/images/splashes/diana.jpg`,
    difficulty: 2,
  },
  {
    id: "draven",
    name: "Draven",
    title: "The Glorious Executioner",
    roles: ["Marksman"],
    image: `/images/champions/draven.jpg`,
    splash: `/images/splashes/draven.jpg`,
    difficulty: 3,
  },
  {
    id: "drmundo",
    name: "Dr. Mundo",
    title: "The Madman of Zaun",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/drmundo.jpg`,
    splash: `/images/splashes/drmundo.jpg`,
    difficulty: 1,
  },
  {
    id: "ekko",
    name: "Ekko",
    title: "The Boy Who Shattered Time",
    roles: ["Assassin", "Fighter"],
    image: `/images/champions/ekko.jpg`,
    splash: `/images/splashes/ekko.jpg`,
    difficulty: 3,
  },
  {
    id: "elise",
    name: "Elise",
    title: "The Spider Queen",
    roles: ["Mage", "Fighter"],
    image: `/images/champions/elise.jpg`,
    splash: `/images/splashes/elise.jpg`,
    difficulty: 3,
  },
  {
    id: "evelynn",
    name: "Evelynn",
    title: "Agony's Embrace",
    roles: ["Assassin", "Mage"],
    image: `/images/champions/evelynn.jpg`,
    splash: `/images/splashes/evelynn.jpg`,
    difficulty: 2,
  },
  {
    id: "ezreal",
    name: "Ezreal",
    title: "The Prodigal Explorer",
    roles: ["Marksman", "Mage"],
    image: `/images/champions/ezreal.jpg`,
    splash: `/images/splashes/ezreal.jpg`,
    difficulty: 2,
  },
  {
    id: "fiddlesticks",
    name: "Fiddlesticks",
    title: "The Ancient Fear",
    roles: ["Mage", "Support"],
    image: `/images/champions/fiddlesticks.jpg`,
    splash: `/images/splashes/fiddlesticks.jpg`,
    difficulty: 2,
  },
  {
    id: "fiora",
    name: "Fiora",
    title: "The Grand Duelist",
    roles: ["Fighter", "Assassin"],
    image: `/images/champions/fiora.jpg`,
    splash: `/images/splashes/fiora.jpg`,
    difficulty: 3,
  },
  {
    id: "fizz",
    name: "Fizz",
    title: "The Tidal Trickster",
    roles: ["Assassin", "Fighter"],
    image: `/images/champions/fizz.jpg`,
    splash: `/images/splashes/fizz.jpg`,
    difficulty: 3,
  },
  {
    id: "galio",
    name: "Galio",
    title: "The Colossus",
    roles: ["Tank", "Mage"],
    image: `/images/champions/galio.jpg`,
    splash: `/images/splashes/galio.jpg`,
    difficulty: 2,
  },
  {
    id: "gangplank",
    name: "Gangplank",
    title: "The Saltwater Scourge",
    roles: ["Fighter"],
    image: `/images/champions/gangplank.jpg`,
    splash: `/images/splashes/gangplank.jpg`,
    difficulty: 3,
  },
  {
    id: "garen",
    name: "Garen",
    title: "The Might of Demacia",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/garen.jpg`,
    splash: `/images/splashes/garen.jpg`,
    difficulty: 1,
  },
  {
    id: "gnar",
    name: "Gnar",
    title: "The Missing Link",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/gnar.jpg`,
    splash: `/images/splashes/gnar.jpg`,
    difficulty: 3,
  },
  {
    id: "gragas",
    name: "Gragas",
    title: "The Rabble Rouser",
    roles: ["Fighter", "Mage"],
    image: `/images/champions/gragas.jpg`,
    splash: `/images/splashes/gragas.jpg`,
    difficulty: 2,
  },
  {
    id: "graves",
    name: "Graves",
    title: "The Outlaw",
    roles: ["Marksman"],
    image: `/images/champions/graves.jpg`,
    splash: `/images/splashes/graves.jpg`,
    difficulty: 2,
  },
  {
    id: "gwen",
    name: "Gwen",
    title: "The Hallowed Seamstress",
    roles: ["Fighter", "Assassin"],
    image: `/images/champions/gwen.jpg`,
    splash: `/images/splashes/gwen.jpg`,
    difficulty: 2,
  },
  {
    id: "hecarim",
    name: "Hecarim",
    title: "The Shadow of War",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/hecarim.jpg`,
    splash: `/images/splashes/hecarim.jpg`,
    difficulty: 2,
  },
  {
    id: "heimerdinger",
    name: "Heimerdinger",
    title: "The Revered Inventor",
    roles: ["Mage", "Support"],
    image: `/images/champions/heimerdinger.jpg`,
    splash: `/images/splashes/heimerdinger.jpg`,
    difficulty: 2,
  },
  {
    id: "illaoi",
    name: "Illaoi",
    title: "The Kraken Priestess",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/illaoi.jpg`,
    splash: `/images/splashes/illaoi.jpg`,
    difficulty: 2,
  },
  {
    id: "irelia",
    name: "Irelia",
    title: "The Blade Dancer",
    roles: ["Fighter", "Assassin"],
    image: `/images/champions/irelia.jpg`,
    splash: `/images/splashes/irelia.jpg`,
    difficulty: 3,
  },
  {
    id: "ivern",
    name: "Ivern",
    title: "The Green Father",
    roles: ["Support", "Mage"],
    image: `/images/champions/ivern.jpg`,
    splash: `/images/splashes/ivern.jpg`,
    difficulty: 3,
  },
  {
    id: "janna",
    name: "Janna",
    title: "The Storm's Fury",
    roles: ["Support", "Mage"],
    image: `/images/champions/janna.jpg`,
    splash: `/images/splashes/janna.jpg`,
    difficulty: 2,
  },
  {
    id: "jarvaniv",
    name: "Jarvan IV",
    title: "The Exemplar of Demacia",
    roles: ["Tank", "Fighter"],
    image: `/images/champions/jarvaniv.jpg`,
    splash: `/images/splashes/jarvaniv.jpg`,
    difficulty: 2,
  },
  {
    id: "jax",
    name: "Jax",
    title: "Grandmaster at Arms",
    roles: ["Fighter", "Assassin"],
    image: `/images/champions/jax.jpg`,
    splash: `/images/splashes/jax.jpg`,
    difficulty: 2,
  },
  {
    id: "jayce",
    name: "Jayce",
    title: "The Defender of Tomorrow",
    roles: ["Fighter", "Marksman"],
    image: `/images/champions/jayce.jpg`,
    splash: `/images/splashes/jayce.jpg`,
    difficulty: 3,
  },
  {
    id: "jhin",
    name: "Jhin",
    title: "The Virtuoso",
    roles: ["Marksman", "Mage"],
    image: `/images/champions/jhin.jpg`,
    splash: `/images/splashes/jhin.jpg`,
    difficulty: 2,
  },
  {
    id: "jinx",
    name: "Jinx",
    title: "The Loose Cannon",
    roles: ["Marksman"],
    image: `/images/champions/jinx.jpg`,
    splash: `/images/splashes/jinx.jpg`,
    difficulty: 2,
  },
  {
    id: "kaisa",
    name: "Kai'Sa",
    title: "Daughter of the Void",
    roles: ["Marksman"],
    image: `/images/champions/kaisa.jpg`,
    splash: `/images/splashes/kaisa.jpg`,
    difficulty: 2,
  },
  {
    id: "kalista",
    name: "Kalista",
    title: "The Spear of Vengeance",
    roles: ["Marksman"],
    image: `/images/champions/kalista.jpg`,
    splash: `/images/splashes/kalista.jpg`,
    difficulty: 3,
  },
  {
    id: "karma",
    name: "Karma",
    title: "The Enlightened One",
    roles: ["Mage", "Support"],
    image: `/images/champions/karma.jpg`,
    splash: `/images/splashes/karma.jpg`,
    difficulty: 2,
  },
  {
    id: "karthus",
    name: "Karthus",
    title: "The Deathsinger",
    roles: ["Mage"],
    image: `/images/champions/karthus.jpg`,
    splash: `/images/splashes/karthus.jpg`,
    difficulty: 2,
  },
  {
    id: "kassadin",
    name: "Kassadin",
    title: "The Void Walker",
    roles: ["Assassin", "Mage"],
    image: `/images/champions/kassadin.jpg`,
    splash: `/images/splashes/kassadin.jpg`,
    difficulty: 3,
  },
  {
    id: "katarina",
    name: "Katarina",
    title: "The Sinister Blade",
    roles: ["Assassin", "Mage"],
    image: `/images/champions/katarina.jpg`,
    splash: `/images/splashes/katarina.jpg`,
    difficulty: 3,
  },
  {
    id: "kayle",
    name: "Kayle",
    title: "The Righteous",
    roles: ["Fighter", "Support"],
    image: `/images/champions/kayle.jpg`,
    splash: `/images/splashes/kayle.jpg`,
    difficulty: 2,
  },
  {
    id: "kayn",
    name: "Kayn",
    title: "The Shadow Reaper",
    roles: ["Fighter", "Assassin"],
    image: `/images/champions/kayn.jpg`,
    splash: `/images/splashes/kayn.jpg`,
    difficulty: 3,
  },
  {
    id: "kennen",
    name: "Kennen",
    title: "The Heart of the Tempest",
    roles: ["Mage", "Marksman"],
    image: `/images/champions/kennen.jpg`,
    splash: `/images/splashes/kennen.jpg`,
    difficulty: 2,
  },
  {
    id: "khazix",
    name: "Kha'Zix",
    title: "The Voidreaver",
    roles: ["Assassin"],
    image: `/images/champions/khazix.jpg`,
    splash: `/images/splashes/khazix.jpg`,
    difficulty: 2,
  },
  {
    id: "kindred",
    name: "Kindred",
    title: "The Eternal Hunters",
    roles: ["Marksman"],
    image: `/images/champions/kindred.jpg`,
    splash: `/images/splashes/kindred.jpg`,
    difficulty: 3,
  },
  {
    id: "kled",
    name: "Kled",
    title: "The Cantankerous Cavalier",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/kled.jpg`,
    splash: `/images/splashes/kled.jpg`,
    difficulty: 2,
  },
  {
    id: "kogmaw",
    name: "Kog'Maw",
    title: "The Mouth of the Abyss",
    roles: ["Marksman", "Mage"],
    image: `/images/champions/kogmaw.jpg`,
    splash: `/images/splashes/kogmaw.jpg`,
    difficulty: 2,
  },
  {
    id: "leblanc",
    name: "LeBlanc",
    title: "The Deceiver",
    roles: ["Assassin", "Mage"],
    image: `/images/champions/leblanc.jpg`,
    splash: `/images/splashes/leblanc.jpg`,
    difficulty: 3,
  },
  {
    id: "leesin",
    name: "Lee Sin",
    title: "The Blind Monk",
    roles: ["Fighter", "Assassin"],
    image: `/images/champions/leesin.jpg`,
    splash: `/images/splashes/leesin.jpg`,
    difficulty: 3,
  },
  {
    id: "leona",
    name: "Leona",
    title: "The Radiant Dawn",
    roles: ["Tank", "Support"],
    image: `/images/champions/leona.jpg`,
    splash: `/images/splashes/leona.jpg`,
    difficulty: 1,
  },
  {
    id: "lillia",
    name: "Lillia",
    title: "The Bashful Bloom",
    roles: ["Fighter", "Mage"],
    image: `/images/champions/lillia.jpg`,
    splash: `/images/splashes/lillia.jpg`,
    difficulty: 2,
  },
  {
    id: "lissandra",
    name: "Lissandra",
    title: "The Ice Witch",
    roles: ["Mage"],
    image: `/images/champions/lissandra.jpg`,
    splash: `/images/splashes/lissandra.jpg`,
    difficulty: 2,
  },
  {
    id: "lucian",
    name: "Lucian",
    title: "The Purifier",
    roles: ["Marksman"],
    image: `/images/champions/lucian.jpg`,
    splash: `/images/splashes/lucian.jpg`,
    difficulty: 2,
  },
  {
    id: "lulu",
    name: "Lulu",
    title: "The Fae Sorceress",
    roles: ["Support", "Mage"],
    image: `/images/champions/lulu.jpg`,
    splash: `/images/splashes/lulu.jpg`,
    difficulty: 2,
  },
  {
    id: "lux",
    name: "Lux",
    title: "The Lady of Luminosity",
    roles: ["Mage", "Support"],
    image: `/images/champions/lux.jpg`,
    splash: `/images/splashes/lux.jpg`,
    difficulty: 1,
  },
  {
    id: "malphite",
    name: "Malphite",
    title: "Shard of the Monolith",
    roles: ["Tank", "Fighter"],
    image: `/images/champions/malphite.jpg`,
    splash: `/images/splashes/malphite.jpg`,
    difficulty: 1,
  },
  {
    id: "malzahar",
    name: "Malzahar",
    title: "The Prophet of the Void",
    roles: ["Mage", "Assassin"],
    image: `/images/champions/malzahar.jpg`,
    splash: `/images/splashes/malzahar.jpg`,
    difficulty: 1,
  },
  {
    id: "maokai",
    name: "Maokai",
    title: "The Twisted Treant",
    roles: ["Tank", "Mage"],
    image: `/images/champions/maokai.jpg`,
    splash: `/images/splashes/maokai.jpg`,
    difficulty: 1,
  },
  {
    id: "masteryi",
    name: "Master Yi",
    title: "The Wuju Bladesman",
    roles: ["Assassin", "Fighter"],
    image: `/images/champions/masteryi.jpg`,
    splash: `/images/splashes/masteryi.jpg`,
    difficulty: 1,
  },
  {
    id: "missfortune",
    name: "Miss Fortune",
    title: "The Bounty Hunter",
    roles: ["Marksman"],
    image: `/images/champions/missfortune.jpg`,
    splash: `/images/splashes/missfortune.jpg`,
    difficulty: 1,
  },
  {
    id: "mordekaiser",
    name: "Mordekaiser",
    title: "The Iron Revenant",
    roles: ["Fighter"],
    image: `/images/champions/mordekaiser.jpg`,
    splash: `/images/splashes/mordekaiser.jpg`,
    difficulty: 2,
  },
  {
    id: "morgana",
    name: "Morgana",
    title: "The Fallen",
    roles: ["Mage", "Support"],
    image: `/images/champions/morgana.jpg`,
    splash: `/images/splashes/morgana.jpg`,
    difficulty: 1,
  },
  {
    id: "nami",
    name: "Nami",
    title: "The Tidecaller",
    roles: ["Support", "Mage"],
    image: `/images/champions/nami.jpg`,
    splash: `/images/splashes/nami.jpg`,
    difficulty: 2,
  },
  {
    id: "nasus",
    name: "Nasus",
    title: "The Curator of the Sands",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/nasus.jpg`,
    splash: `/images/splashes/nasus.jpg`,
    difficulty: 2,
  },
  {
    id: "nautilus",
    name: "Nautilus",
    title: "The Titan of the Depths",
    roles: ["Tank", "Support"],
    image: `/images/champions/nautilus.jpg`,
    splash: `/images/splashes/nautilus.jpg`,
    difficulty: 2,
  },
  {
    id: "neeko",
    name: "Neeko",
    title: "The Curious Chameleon",
    roles: ["Mage", "Support"],
    image: `/images/champions/neeko.jpg`,
    splash: `/images/splashes/neeko.jpg`,
    difficulty: 2,
  },
  {
    id: "nidalee",
    name: "Nidalee",
    title: "The Bestial Huntress",
    roles: ["Assassin", "Mage"],
    image: `/images/champions/nidalee.jpg`,
    splash: `/images/splashes/nidalee.jpg`,
    difficulty: 3,
  },
  {
    id: "nocturne",
    name: "Nocturne",
    title: "The Eternal Nightmare",
    roles: ["Assassin", "Fighter"],
    image: `/images/champions/nocturne.jpg`,
    splash: `/images/splashes/nocturne.jpg`,
    difficulty: 2,
  },
  {
    id: "nunu",
    name: "Nunu & Willump",
    title: "The Boy and His Yeti",
    roles: ["Tank", "Fighter"],
    image: `/images/champions/nunu.jpg`,
    splash: `/images/splashes/nunu.jpg`,
    difficulty: 1,
  },
  {
    id: "olaf",
    name: "Olaf",
    title: "The Berserker",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/olaf.jpg`,
    splash: `/images/splashes/olaf.jpg`,
    difficulty: 2,
  },
  {
    id: "orianna",
    name: "Orianna",
    title: "The Lady of Clockwork",
    roles: ["Mage", "Support"],
    image: `/images/champions/orianna.jpg`,
    splash: `/images/splashes/orianna.jpg`,
    difficulty: 3,
  },
  {
    id: "ornn",
    name: "Ornn",
    title: "The Fire Below the Mountain",
    roles: ["Tank", "Fighter"],
    image: `/images/champions/ornn.jpg`,
    splash: `/images/splashes/ornn.jpg`,
    difficulty: 2,
  },
  {
    id: "pantheon",
    name: "Pantheon",
    title: "The Unbreakable Spear",
    roles: ["Fighter", "Assassin"],
    image: `/images/champions/pantheon.jpg`,
    splash: `/images/splashes/pantheon.jpg`,
    difficulty: 2,
  },
  {
    id: "poppy",
    name: "Poppy",
    title: "Keeper of the Hammer",
    roles: ["Tank", "Fighter"],
    image: `/images/champions/poppy.jpg`,
    splash: `/images/splashes/poppy.jpg`,
    difficulty: 2,
  },
  {
    id: "pyke",
    name: "Pyke",
    title: "The Bloodharbor Ripper",
    roles: ["Support", "Assassin"],
    image: `/images/champions/pyke.jpg`,
    splash: `/images/splashes/pyke.jpg`,
    difficulty: 2,
  },
  {
    id: "qiyana",
    name: "Qiyana",
    title: "Empress of the Elements",
    roles: ["Assassin", "Fighter"],
    image: `/images/champions/qiyana.jpg`,
    splash: `/images/splashes/qiyana.jpg`,
    difficulty: 2,
  },
  {
    id: "quinn",
    name: "Quinn",
    title: "Demacia's Wings",
    roles: ["Marksman", "Assassin"],
    image: `/images/champions/quinn.jpg`,
    splash: `/images/splashes/quinn.jpg`,
    difficulty: 2,
  },
  {
    id: "rakan",
    name: "Rakan",
    title: "The Charmer",
    roles: ["Support"],
    image: `/images/champions/rakan.jpg`,
    splash: `/images/splashes/rakan.jpg`,
    difficulty: 2,
  },
  {
    id: "rammus",
    name: "Rammus",
    title: "The Armordillo",
    roles: ["Tank", "Fighter"],
    image: `/images/champions/rammus.jpg`,
    splash: `/images/splashes/rammus.jpg`,
    difficulty: 1,
  },
  {
    id: "reksai",
    name: "Rek'Sai",
    title: "The Void Burrower",
    roles: ["Fighter"],
    image: `/images/champions/reksai.jpg`,
    splash: `/images/splashes/reksai.jpg`,
    difficulty: 2,
  },
  {
    id: "rell",
    name: "Rell",
    title: "The Iron Maiden",
    roles: ["Tank", "Support"],
    image: `/images/champions/rell.jpg`,
    splash: `/images/splashes/rell.jpg`,
    difficulty: 2,
  },
  {
    id: "renekton",
    name: "Renekton",
    title: "The Butcher of the Sands",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/renekton.jpg`,
    splash: `/images/splashes/renekton.jpg`,
    difficulty: 2,
  },
  {
    id: "rengar",
    name: "Rengar",
    title: "The Pridestalker",
    roles: ["Assassin", "Fighter"],
    image: `/images/champions/rengar.jpg`,
    splash: `/images/splashes/rengar.jpg`,
    difficulty: 3,
  },
  {
    id: "riven",
    name: "Riven",
    title: "The Exile",
    roles: ["Fighter", "Assassin"],
    image: `/images/champions/riven.jpg`,
    splash: `/images/splashes/riven.jpg`,
    difficulty: 3,
  },
  {
    id: "rumble",
    name: "Rumble",
    title: "The Mechanized Menace",
    roles: ["Fighter", "Mage"],
    image: `/images/champions/rumble.jpg`,
    splash: `/images/splashes/rumble.jpg`,
    difficulty: 3,
  },
  {
    id: "ryze",
    name: "Ryze",
    title: "The Rune Mage",
    roles: ["Mage", "Fighter"],
    image: `/images/champions/ryze.jpg`,
    splash: `/images/splashes/ryze.jpg`,
    difficulty: 3,
  },
  {
    id: "samira",
    name: "Samira",
    title: "The Desert Rose",
    roles: ["Marksman"],
    image: `/images/champions/samira.jpg`,
    splash: `/images/splashes/samira.jpg`,
    difficulty: 3,
  },
  {
    id: "sejuani",
    name: "Sejuani",
    title: "Fury of the North",
    roles: ["Tank", "Fighter"],
    image: `/images/champions/sejuani.jpg`,
    splash: `/images/splashes/sejuani.jpg`,
    difficulty: 2,
  },
  {
    id: "senna",
    name: "Senna",
    title: "The Redeemer",
    roles: ["Marksman", "Support"],
    image: `/images/champions/senna.jpg`,
    splash: `/images/splashes/senna.jpg`,
    difficulty: 2,
  },
  {
    id: "seraphine",
    name: "Seraphine",
    title: "The Starry-Eyed Songstress",
    roles: ["Mage", "Support"],
    image: `/images/champions/seraphine.jpg`,
    splash: `/images/splashes/seraphine.jpg`,
    difficulty: 1,
  },
  {
    id: "sett",
    name: "Sett",
    title: "The Boss",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/sett.jpg`,
    splash: `/images/splashes/sett.jpg`,
    difficulty: 1,
  },
  {
    id: "shaco",
    name: "Shaco",
    title: "The Demon Jester",
    roles: ["Assassin"],
    image: `/images/champions/shaco.jpg`,
    splash: `/images/splashes/shaco.jpg`,
    difficulty: 3,
  },
  {
    id: "shen",
    name: "Shen",
    title: "The Eye of Twilight",
    roles: ["Tank"],
    image: `/images/champions/shen.jpg`,
    splash: `/images/splashes/shen.jpg`,
    difficulty: 2,
  },
  {
    id: "shyvana",
    name: "Shyvana",
    title: "The Half-Dragon",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/shyvana.jpg`,
    splash: `/images/splashes/shyvana.jpg`,
    difficulty: 1,
  },
  {
    id: "singed",
    name: "Singed",
    title: "The Mad Chemist",
    roles: ["Tank", "Fighter"],
    image: `/images/champions/singed.jpg`,
    splash: `/images/splashes/singed.jpg`,
    difficulty: 2,
  },
  {
    id: "sion",
    name: "Sion",
    title: "The Undead Juggernaut",
    roles: ["Tank", "Fighter"],
    image: `/images/champions/sion.jpg`,
    splash: `/images/splashes/sion.jpg`,
    difficulty: 2,
  },
  {
    id: "sivir",
    name: "Sivir",
    title: "The Battle Mistress",
    roles: ["Marksman"],
    image: `/images/champions/sivir.jpg`,
    splash: `/images/splashes/sivir.jpg`,
    difficulty: 1,
  },
  {
    id: "skarner",
    name: "Skarner",
    title: "The Crystal Vanguard",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/skarner.jpg`,
    splash: `/images/splashes/skarner.jpg`,
    difficulty: 2,
  },
  {
    id: "sona",
    name: "Sona",
    title: "Maven of the Strings",
    roles: ["Support", "Mage"],
    image: `/images/champions/sona.jpg`,
    splash: `/images/splashes/sona.jpg`,
    difficulty: 1,
  },
  {
    id: "soraka",
    name: "Soraka",
    title: "The Starchild",
    roles: ["Support", "Mage"],
    image: `/images/champions/soraka.jpg`,
    splash: `/images/splashes/soraka.jpg`,
    difficulty: 1,
  },
  {
    id: "swain",
    name: "Swain",
    title: "The Noxian Grand General",
    roles: ["Mage", "Fighter"],
    image: `/images/champions/swain.jpg`,
    splash: `/images/splashes/swain.jpg`,
    difficulty: 2,
  },
  {
    id: "sylas",
    name: "Sylas",
    title: "The Unshackled",
    roles: ["Mage", "Assassin"],
    image: `/images/champions/sylas.jpg`,
    splash: `/images/splashes/sylas.jpg`,
    difficulty: 3,
  },
  {
    id: "syndra",
    name: "Syndra",
    title: "The Dark Sovereign",
    roles: ["Mage"],
    image: `/images/champions/syndra.jpg`,
    splash: `/images/splashes/syndra.jpg`,
    difficulty: 3,
  },
  {
    id: "tahmkench",
    name: "Tahm Kench",
    title: "The River King",
    roles: ["Support", "Tank"],
    image: `/images/champions/tahmkench.jpg`,
    splash: `/images/splashes/tahmkench.jpg`,
    difficulty: 2,
  },
  {
    id: "taliyah",
    name: "Taliyah",
    title: "The Stoneweaver",
    roles: ["Mage", "Support"],
    image: `/images/champions/taliyah.jpg`,
    splash: `/images/splashes/taliyah.jpg`,
    difficulty: 3,
  },
  {
    id: "talon",
    name: "Talon",
    title: "The Blade's Shadow",
    roles: ["Assassin"],
    image: `/images/champions/talon.jpg`,
    splash: `/images/splashes/talon.jpg`,
    difficulty: 2,
  },
  {
    id: "taric",
    name: "Taric",
    title: "The Shield of Valoran",
    roles: ["Support", "Fighter"],
    image: `/images/champions/taric.jpg`,
    splash: `/images/splashes/taric.jpg`,
    difficulty: 2,
  },
  {
    id: "teemo",
    name: "Teemo",
    title: "The Swift Scout",
    roles: ["Marksman", "Assassin"],
    image: `/images/champions/teemo.jpg`,
    splash: `/images/splashes/teemo.jpg`,
    difficulty: 1,
  },
  {
    id: "thresh",
    name: "Thresh",
    title: "The Chain Warden",
    roles: ["Support", "Fighter"],
    image: `/images/champions/thresh.jpg`,
    splash: `/images/splashes/thresh.jpg`,
    difficulty: 3,
  },
  {
    id: "tristana",
    name: "Tristana",
    title: "The Yordle Gunner",
    roles: ["Marksman", "Assassin"],
    image: `/images/champions/tristana.jpg`,
    splash: `/images/splashes/tristana.jpg`,
    difficulty: 1,
  },
  {
    id: "trundle",
    name: "Trundle",
    title: "The Troll King",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/trundle.jpg`,
    splash: `/images/splashes/trundle.jpg`,
    difficulty: 1,
  },
  {
    id: "tryndamere",
    name: "Tryndamere",
    title: "The Barbarian King",
    roles: ["Fighter", "Assassin"],
    image: `/images/champions/tryndamere.jpg`,
    splash: `/images/splashes/tryndamere.jpg`,
    difficulty: 1,
  },
  {
    id: "twistedfate",
    name: "Twisted Fate",
    title: "The Card Master",
    roles: ["Mage"],
    image: `/images/champions/twistedfate.jpg`,
    splash: `/images/splashes/twistedfate.jpg`,
    difficulty: 2,
  },
  {
    id: "twitch",
    name: "Twitch",
    title: "The Plague Rat",
    roles: ["Marksman", "Assassin"],
    image: `/images/champions/twitch.jpg`,
    splash: `/images/splashes/twitch.jpg`,
    difficulty: 2,
  },
  {
    id: "udyr",
    name: "Udyr",
    title: "The Spirit Walker",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/udyr.jpg`,
    splash: `/images/splashes/udyr.jpg`,
    difficulty: 2,
  },
  {
    id: "urgot",
    name: "Urgot",
    title: "The Dreadnought",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/urgot.jpg`,
    splash: `/images/splashes/urgot.jpg`,
    difficulty: 2,
  },
  {
    id: "varus",
    name: "Varus",
    title: "The Arrow of Retribution",
    roles: ["Marksman", "Mage"],
    image: `/images/champions/varus.jpg`,
    splash: `/images/splashes/varus.jpg`,
    difficulty: 2,
  },
  {
    id: "vayne",
    name: "Vayne",
    title: "The Night Hunter",
    roles: ["Marksman", "Assassin"],
    image: `/images/champions/vayne.jpg`,
    splash: `/images/splashes/vayne.jpg`,
    difficulty: 3,
  },
  {
    id: "veigar",
    name: "Veigar",
    title: "The Tiny Master of Evil",
    roles: ["Mage"],
    image: `/images/champions/veigar.jpg`,
    splash: `/images/splashes/veigar.jpg`,
    difficulty: 2,
  },
  {
    id: "velkoz",
    name: "Vel'Koz",
    title: "The Eye of the Void",
    roles: ["Mage"],
    image: `/images/champions/velkoz.jpg`,
    splash: `/images/splashes/velkoz.jpg`,
    difficulty: 2,
  },
  {
    id: "vi",
    name: "Vi",
    title: "The Piltover Enforcer",
    roles: ["Fighter", "Assassin"],
    image: `/images/champions/vi.jpg`,
    splash: `/images/splashes/vi.jpg`,
    difficulty: 2,
  },
  {
    id: "viego",
    name: "Viego",
    title: "The Ruined King",
    roles: ["Assassin", "Fighter"],
    image: `/images/champions/viego.jpg`,
    splash: `/images/splashes/viego.jpg`,
    difficulty: 2,
  },
  {
    id: "viktor",
    name: "Viktor",
    title: "The Machine Herald",
    roles: ["Mage"],
    image: `/images/champions/viktor.jpg`,
    splash: `/images/splashes/viktor.jpg`,
    difficulty: 3,
  },
  {
    id: "vladimir",
    name: "Vladimir",
    title: "The Crimson Reaper",
    roles: ["Mage"],
    image: `/images/champions/vladimir.jpg`,
    splash: `/images/splashes/vladimir.jpg`,
    difficulty: 2,
  },
  {
    id: "volibear",
    name: "Volibear",
    title: "The Relentless Storm",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/volibear.jpg`,
    splash: `/images/splashes/volibear.jpg`,
    difficulty: 2,
  },
  {
    id: "warwick",
    name: "Warwick",
    title: "The Uncaged Wrath of Zaun",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/warwick.jpg`,
    splash: `/images/splashes/warwick.jpg`,
    difficulty: 1,
  },
  {
    id: "wukong",
    name: "Wukong",
    title: "The Monkey King",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/wukong.jpg`,
    splash: `/images/splashes/wukong.jpg`,
    difficulty: 2,
  },
  {
    id: "xayah",
    name: "Xayah",
    title: "The Rebel",
    roles: ["Marksman"],
    image: `/images/champions/xayah.jpg`,
    splash: `/images/splashes/xayah.jpg`,
    difficulty: 2,
  },
  {
    id: "xerath",
    name: "Xerath",
    title: "The Magus Ascendant",
    roles: ["Mage"],
    image: `/images/champions/xerath.jpg`,
    splash: `/images/splashes/xerath.jpg`,
    difficulty: 2,
  },
  {
    id: "xinzhao",
    name: "Xin Zhao",
    title: "The Seneschal of Demacia",
    roles: ["Fighter", "Assassin"],
    image: `/images/champions/xinzhao.jpg`,
    splash: `/images/splashes/xinzhao.jpg`,
    difficulty: 1,
  },
  {
    id: "yasuo",
    name: "Yasuo",
    title: "The Unforgiven",
    roles: ["Fighter", "Assassin"],
    image: `/images/champions/yasuo.jpg`,
    splash: `/images/splashes/yasuo.jpg`,
    difficulty: 3,
  },
  {
    id: "yone",
    name: "Yone",
    title: "The Unforgotten",
    roles: ["Assassin", "Fighter"],
    image: `/images/champions/yone.jpg`,
    splash: `/images/splashes/yone.jpg`,
    difficulty: 3,
  },
  {
    id: "yorick",
    name: "Yorick",
    title: "Shepherd of Souls",
    roles: ["Fighter", "Tank"],
    image: `/images/champions/yorick.jpg`,
    splash: `/images/splashes/yorick.jpg`,
    difficulty: 2,
  },
  {
    id: "yuumi",
    name: "Yuumi",
    title: "The Magical Cat",
    roles: ["Support", "Mage"],
    image: `/images/champions/yuumi.jpg`,
    splash: `/images/splashes/yuumi.jpg`,
    difficulty: 1,
  },
  {
    id: "zac",
    name: "Zac",
    title: "The Secret Weapon",
    roles: ["Tank", "Fighter"],
    image: `/images/champions/zac.jpg`,
    splash: `/images/splashes/zac.jpg`,
    difficulty: 1,
  },
  {
    id: "zed",
    name: "Zed",
    title: "The Master of Shadows",
    roles: ["Assassin"],
    image: `/images/champions/zed.jpg`,
    splash: `/images/splashes/zed.jpg`,
    difficulty: 3,
  },
  {
    id: "ziggs",
    name: "Ziggs",
    title: "The Hexplosives Expert",
    roles: ["Mage"],
    image: `/images/champions/ziggs.jpg`,
    splash: `/images/splashes/ziggs.jpg`,
    difficulty: 2,
  },
  {
    id: "zilean",
    name: "Zilean",
    title: "The Chronokeeper",
    roles: ["Support", "Mage"],
    image: `/images/champions/zilean.jpg`,
    splash: `/images/splashes/zilean.jpg`,
    difficulty: 2,
  },
  {
    id: "zoe",
    name: "Zoe",
    title: "The Aspect of Twilight",
    roles: ["Mage", "Support"],
    image: `/images/champions/zoe.jpg`,
    splash: `/images/splashes/zoe.jpg`,
    difficulty: 3,
  },
  {
    id: "zyra",
    name: "Zyra",
    title: "Rise of the Thorns",
    roles: ["Mage", "Support"],
    image: `/images/champions/zyra.jpg`,
    splash: `/images/splashes/zyra.jpg`,
    difficulty: 2,
  },
]
