// Dados de campeões em destaque por função para o carrossel

export const featuredChampions = {
  TOP: [
    {
      id: "darius",
      name: "Darius",
      title: "The Hand of Noxus",
      role: "TOP",
      image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Darius_0.jpg",
      winRate: "53.2%",
    },
    {
      id: "garen",
      name: "Garen",
      title: "The Might of Demacia",
      role: "TOP",
      image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Garen_0.jpg",
      winRate: "51.8%",
    },
    {
      id: "sett",
      name: "Sett",
      title: "The Boss",
      role: "TOP",
      image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sett_0.jpg",
      winRate: "50.5%",
    },
  ],
  JUNGLE: [
    {
      id: "leesin",
      name: "Lee Sin",
      title: "The Blind Monk",
      role: "JUNGLE",
      image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/LeeSin_0.jpg",
      winRate: "49.8%",
    },
    {
      id: "khazix",
      name: "Kha'Zix",
      title: "The Voidreaver",
      role: "JUNGLE",
      image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Khazix_0.jpg",
      winRate: "52.1%",
    },
    {
      id: "hecarim",
      name: "Hecarim",
      title: "The Shadow of War",
      role: "JUNGLE",
      image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Hecarim_0.jpg",
      winRate: "51.3%",
    },
  ],
  MID: [
    {
      id: "yasuo",
      name: "Yasuo",
      title: "The Unforgiven",
      role: "MID",
      image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yasuo_0.jpg",
      winRate: "48.9%",
    },
    {
      id: "ahri",
      name: "Ahri",
      title: "The Nine-Tailed Fox",
      role: "MID",
      image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg",
      winRate: "51.2%",
    },
    {
      id: "zed",
      name: "Zed",
      title: "The Master of Shadows",
      role: "MID",
      image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zed_0.jpg",
      winRate: "50.7%",
    },
  ],
  ADC: [
    {
      id: "jinx",
      name: "Jinx",
      title: "The Loose Cannon",
      role: "ADC",
      image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jinx_0.jpg",
      winRate: "52.4%",
    },
    {
      id: "caitlyn",
      name: "Caitlyn",
      title: "The Sheriff of Piltover",
      role: "ADC",
      image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Caitlyn_0.jpg",
      winRate: "50.9%",
    },
    {
      id: "kaisa",
      name: "Kai'Sa",
      title: "Daughter of the Void",
      role: "ADC",
      image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kaisa_0.jpg",
      winRate: "51.6%",
    },
  ],
  SUPPORT: [
    {
      id: "thresh",
      name: "Thresh",
      title: "The Chain Warden",
      role: "SUPPORT",
      image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Thresh_0.jpg",
      winRate: "50.2%",
    },
    {
      id: "lulu",
      name: "Lulu",
      title: "The Fae Sorceress",
      role: "SUPPORT",
      image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lulu_0.jpg",
      winRate: "53.1%",
    },
    {
      id: "pyke",
      name: "Pyke",
      title: "The Bloodharbor Ripper",
      role: "SUPPORT",
      image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pyke_0.jpg",
      winRate: "49.7%",
    },
  ],
}
